
### GET
GET http://localhost:3000/flors

### GET
GET http://localhost:3000/flors/77


###

POST http://localhost:3000/flors
Content-Type: application/json

{
    "name": "ITB",
    "category": "Tecnològica",
    "bloomSeason": "Estiu",
    "type": "flor"
}

###

DELETE http://localhost:3000/flors/7

###

PUT http://localhost:3000/flors/1
Content-Type: application/json

{
    "name": "Rosal",
    "category": "categoria modificada",
    "bloomSeason": "Estiu",
    "type": "flor"
}

###